### ISSUE TITLE
ios 11 errors

### ISSUE THREAD

**Issue by rtcwp07** [saebekassebil/microphone-stream#13]
Trying to hook up some watson-speech voice recognition (which has a dependency on this module through its recognize-microphone module) in ios 11 mobile safari, which at long last supports getUserMedia.  After many trials and errors am still unable to pin down the exact issue I'm facing but I keep getting errors like
`[Log] speech error:  – TypeError: null is not an object (evaluating 'h.createScriptProcessor') — a8997354c29673cc5683620ba2cbcbf7e58f59d0.js:25:993451 (a8997354c29673cc5683620ba2cbcbf7e58f59d0.js, line 339)
TypeError: null is not an object (evaluating 'h.createScriptProcessor') — a8997354c29673cc5683620ba2cbcbf7e58f59d0.js:25:993451`
and
`[Log] speech error:  – TypeError: null is not an object (evaluating 'h.createMediaStreamSource') — a8997354c29673cc5683620ba2cbcbf7e58f59d0.js:25:993451 (a8997354c29673cc5683620ba2cbcbf7e58f59d0.js, line 339)
TypeError: null is not an object (evaluating 'h.createMediaStreamSource') — a8997354c29673cc5683620ba2cbcbf7e58f59d0.js:25:993451`

Anybody seen anything like this or been able to successfully getUserMedia via this module on ios 11?  Thanks.

**Comment by nfriedly** [comment]
I've only looked into it briefly but haven't gotten it working yet so far. 

Update: Digging in more now. I haven't gotten that particular error. On an iPod touch, I kept getting an OverconstrainedError and eventually realized that Safari there doesn't think it has a microphone (it does), so it only allows video access.

Switching to an iPad, I got it to not throw any errors.. but never actually work either. In my case, both `audioContext.createMediaStreamSource(stream)`, and  `audioContext.createScriptProcessor()` appear to work, but the latter's `onaudioprocess` event never fires. I'm digging in more.  

This is a better SO link - it looks like no one else has solved the issue either: https://stackoverflow.com/questions/46363048/onaudioprocess-not-called-on-ios11

**Comment by rtcwp07** [comment]
Got it working by modifying my locally installed microphone-stream to use the Howler.js AudioContext that my app was already using.  I guess mobile safari doesn't like more than one AudioContext?

**Comment by nfriedly** [comment]
I'm not sure about multiple AudioContexts. The problem I found is that Safari automatically suspends the AudioContext, and you can only resume it in response to a tap. If you wait until you have the MediaStream instance, it's too late to resume - you'll need a second tap.

I'm releasing a v4 of this library that doesn't expect the MediaStream to be passed to the constructor, and instead provides a new setStream() method. You create the MicrophoneStream instance synchronously in response to the tap, call getUserMedia(), and then asynchronously connect the the two after getUserMedia() resolves with a MediaStream.

But you version works too. If you'd like, we can make the AudioContext an optional param to be passed in.
