### ISSUE TITLE
ReferenceError: describe is not defined

### ISSUE THREAD

**Issue by mimoraes** [saebekassebil/microphone-stream#17]
pi@Rose:~/node/node_modules/microphone-stream/test $ node spec.js 
/home/pi/node/node_modules/microphone-stream/test/spec.js:12
describe('MicrophoneStream', function() {
^

ReferenceError: describe is not defined
    at Object.<anonymous> (/home/pi/node/node_modules/microphone-stream/test/spec.js:12:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
pi@Rose:~/node/node_modules/microphone-stream/test $

**Comment by mimoraes** [comment]
`
pi@Rose:~/node/node_modules/microphone-stream $ cat package.json 
{
  "_args": [
    [
      {
        "raw": "microphone-stream",
        "scope": null,
        "escapedName": "microphone-stream",
        "name": "microphone-stream",
        "rawSpec": "",
        "spec": "latest",
        "type": "tag"
      },
      "/home/pi/node"
    ]
  ],
  "_from": "microphone-stream@latest",
  "_id": "microphone-stream@4.1.2",
  "_inCache": true,
  "_location": "/microphone-stream",
  "_nodeVersion": "9.0.0",
  "_npmOperationalInternal": {
    "host": "s3://npm-registry-packages",
    "tmp": "tmp/microphone-stream-4.1.2.tgz_1509547082775_0.9543836147058755"
  },
  "_npmUser": {
    "name": "nfriedly",
    "email": "nathan@nfriedly.com"
  },
  "_npmVersion": "5.5.1",
  "_phantomChildren": {},
  "_requested": {
    "raw": "microphone-stream",
    "scope": null,
    "escapedName": "microphone-stream",
    "name": "microphone-stream",
    "rawSpec": "",
    "spec": "latest",
    "type": "tag"
  },
  "_requiredBy": [
    "#USER"
  ],
  "_resolved": "https://registry.npmjs.org/microphone-stream/-/microphone-stream-4.1.2.tgz",
  "_shasum": "4c2567ac13c875a13b129460ec14fbc92ebc73a8",
  "_shrinkwrap": null,
  "_spec": "microphone-stream",
  "_where": "/home/pi/node",
  "author": {
    "name": "Jakob Miland",
    "email": "saebekassebil@gmail.com"
  },
  "bugs": {
    "url": "https://github.com/saebekassebil/microphone-stream/issues"
  },
  "contributors": [
    {
      "name": "Nathan Friedly",
      "url": "http://nfriedly.com"
    }
  ],
  "dependencies": {
    "buffer-from": "^0.1.1"
  },
  "description": "A stream of raw audio data from the microphone for use in browsers with getUserMedia",
  "devDependencies": {
    "browserify": "^14.4.0",
    "eslint": "^4.8.0",
    "eslint-config-google": "^0.9.1",
    "get-user-media-promise": "^1.0.0",
    "karma": "^1.7.1",
    "karma-browserify": "^5.0.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-mocha": "^1.3.0",
    "mocha": "^3.5.3"
  },
  "directories": {},
  "dist": {
    "integrity": "sha512-u6ZNivZXVabz1DPSpUZNvv+mOOp6CQ/8LiGC7349nFORSVpUDla50YFb2/SzOGs8Zku6i78Xw9hHNV8iUikn8A==",
    "shasum": "4c2567ac13c875a13b129460ec14fbc92ebc73a8",
    "tarball": "https://registry.npmjs.org/microphone-stream/-/microphone-stream-4.1.2.tgz"
  },
  "gitHead": "0827640245ed09a899012530f9641df9c1bbfb8c",
  "homepage": "https://github.com/saebekassebil/microphone-stream#readme",
  "keywords": [
    "webrtc",
    "getUserMedia",
    "WebAudio",
    "audio",
    "microphone",
    "stream",
    "record"
  ],
  "license": "MIT",
  "main": "microphone-stream.js",
  "maintainers": [
    {
      "name": "nfriedly",
      "email": "nathan@nfriedly.com"
    },
    {
      "name": "saebekassebil",
      "email": "saebekassebil@gmail.com"
    }
  ],
  "name": "microphone-stream",
  "optionalDependencies": {},
  "readme": "ERROR: No README data found!",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/saebekassebil/microphone-stream.git"
  },
  "scripts": {
    "autofix": "eslint . --fix",
    "lint": "eslint .",
    "test": "npm run lint && npm run test-integration",
    "test-integration": "karma start --single-run",
    "watch": "karma start"
  },
  "version": "4.1.2"
}
`

**Comment by nfriedly** [comment]
Run the command `npm test` instead of executing the spec file directly.
These tests use Moca, which defines all of the required variables before
executing the test files.

In general, in npm test is almost always the correct way to execute nodejs
tests.
