### ISSUE TITLE
Static when saving

### ISSUE THREAD

**Issue by ghost** [saebekassebil/microphone-stream#19]
Hello,

I am streaming the float32arrays to a python websocket server and saving the audio files using Scipy.io.wavfile.write.

When I play the file I hear mostly static but can slightly hear the underlying words that I recorded. Any advice?

**Comment by nfriedly** [comment]
It's hard to say; the 32-bit float format isn't very common in wav files. You might want to try converting to the more common 16-bit PCM format, and see if that helps. This stream converts it and downsamples  to 16khz: 
https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/speech-to-text/webaudio-l16-stream.js 

(In addition to being a more common format, it also saves quite a bit of bandwidth ;)

**Comment by ghost** [comment]
Thank you for the tip and direction @nfriedly 

Here is what I am currently doing / seeing:
1. On 'format' I am setting the Watson l16 stream and sending the audio to it through a pipe. I have objectMode: true on micStream and l16-stream. 
`micStream.on('format', function(format) {
    console.log(format);
    let l16Stream = new WebAudiol16Stream({
        sourceSampleRate: format.sampleRate,
        downsample: true,
        objectMode: true, // should be set to the same as micstreeams
    });
    micStream.pipe(l16Stream).pipe(echoStream);
});`

2. I've created a writeable stream 'echoStream' to get the chunks and send them through my socket.
I am currently getting uint8arrays from the pipe into echoStream. According to your previous email shouldn't these be int16arrays?

Although the data looks odd.. it's always really close to 0 or 255
`0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 2, 0, 3, 0, 3, 0, 3, 0, 4, 0, 2, 0, 1, 0, 2, 0, 4, 0, 4, 0, 4, 0, 4, 0, 3, 0, 4, 0, 3, 0, 4, 0, 2, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 4, 0, 5, 0, 5, 0, 4, 0, 6, 0, 8, 0, 8, 0, 8, 0, 9, 0, 7, 0, 5, 0, 6, 0, 5, 0, 4, 0, 4, 0, 1, 0, 1, 0, 0, 0, 253, 255, 251, 255, 250, 255, 250, 255, 250, 255, 250, 255, 249, 255, 249, 255, 250, 255, 252, 255, 0, 0, 0, 0, 253, 255, 254, 255, 254, 255, 253, 255, 252, 255, 252, 255, 252, 255, 252, 255, 251, 255, 251, 255, 252, 255, 254, 255, 0, 0, 1, 0, 2, 0, 1, 0, 0, 0, 0, 0, 254, 255, 254, 255, 252, 255, 253, 255, 251, 255, 248, 255, 246, 255, 248, 255, 250, 255, 250, 255, 250, 255, 250, 255, 250, 255, 250, 255, 250, 255, 250, 255, 250, 255, 250, 255, 249, 255, 250, 255, 251, 255]`

When I convert the array from uint8 to an array of int I am passing it to my server where I recover the array to uint8 in numpy and pass to Scipy to write the wav file which takes any of the following:

WAV format | Min | Max | NumPy dtype
-- | -- | -- | --
32-bit floating-point | -1.0 | +1.0 | float32
32-bit PCM | -2147483648 | +2147483647 | int32
16-bit PCM | -32768 | +32767 | int16
8-bit PCM | 0 | 255 | uint8

So it should be able to take the uint8 however with all of the data being so close to each bound of uint8 the resulting audio file looks like this:
![image](https://user-images.githubusercontent.com/28879452/32693190-aa0916c8-c6f4-11e7-8cca-20864e3f87d7.png)

**Comment by tcollins590** [comment]
It seems micStream is outputting uint8array through the pipe when the watson l16 utility requires float32array.

**Comment by nfriedly** [comment]
Node.js streams are either binary or object 
mode. Binary mode uses Buffers which are basically just Uint8Arrays, regardless of the underlying data.

Reguadless of the input mode, the Watson L16 stream always outputs in binary mode, so that's working properly. 

You're right about the output seeming odd, but you're looking at 8-bit chunks of 16-bit data. Try doing `new Int16Array(chunk.buffer)` and see if  it looks more realistic. Also check out the original float 32 values.

Finally, test with https://watson-speech.mybluemix.net/microphone-streaming.html just to make sure you're getting good data from the browser.

**Comment by ghost** [comment]
Adding `new Int16Array(chunk.buffer)` after receiving the pipe back from Watsons encoder seems to solve the issue. 

The file is saving fine.

Thank you!

**Comment by nfriedly** [comment]
Great, glad to hear it's working. I'm not sure what the deal with float-32 wav files is, but I've never had much success with them.
