### ISSUE TITLE
why sometimes show 0 seconds recording?

### ISSUE THREAD

**Issue by mingyuesun** [saebekassebil/microphone-stream#21]
hello,I Want to ask, in the use of this recording plug-in, has tapped the button, recorded about four or five seconds and has access to the recording rights, why sometimes show 0 seconds recording?

**Comment by nfriedly** [comment]
Hi @MingyueSun 

I'm not sure.. perhaps a mix-up between binary and object mode? Or maybe there's just a bug that I'm not aware of. Can you give me a reproducible test case?

**Comment by mingyuesun** [comment]
Oh, okay.
Why is this plugin not supported on safari with iphone version 11.2.6? But I think your version support is more than 11.2.
![image](https://user-images.githubusercontent.com/31138694/37588935-ab8802a2-2b9e-11e8-920f-26506d72597e.png)
![image](https://user-images.githubusercontent.com/31138694/37588940-b3b180d4-2b9e-11e8-96bd-8e42d3282578.png)

**Comment by nfriedly** [comment]
Is the MicrophoneStream instance being created in _direct_ response to a tap? That is the only time iOS allows microphone access to be initialized. If there's an ajax request, or a promise, or a setTimeout, or anythig like that, iOS will go back to it's default behavior of blocking microphone access. The [example in the readme](https://github.com/saebekassebil/microphone-stream#example) shows this set up correctly, with the micStream instance being created in an onClick event handler.

I don't own an iPhone, but the last time I tested on one, it worked. Try out this demo (which uses microphone-stream under the hood) and let me know if it works on your iPhone: https://watson-speech.mybluemix.net/microphone-streaming-preload-token.html

Also, I'm not sure what the error message says, can you translate it for me?
