### ISSUE TITLE
Best way to handle the stream in node?

### ISSUE THREAD

**Issue by mshaaban0** [saebekassebil/microphone-stream#22]
Hello, I'm trying to create a live audio broadcasting service, by getting the stream from the browser mic, and send it to node through `enigne.io` (WebSocket).

I'm wondering what would be the best way to handle the stream in node, the end goal should be saving the stream to an audio file in parallell with broadcasting the data and encoding it to audio on the browser.

I'd appreaciate if someone can take a look on the code...

**Server.js**
```javascript
const express = require('express');
const app = express();
const engine = require('engine.io');
const port = 4000;
const server = engine.listen(port);
const fs = require('fs');
const { Readable } = require('stream');

const FileWriter = require('wav').FileWriter;

server.on('connection', (socket) => {
  console.log('Sup! from server');
  // let writeableStream = fs.createWriteStream('output.wav');
  socket.on('message', (data) => {
    const stream = new Readable();
    stream.push(data);
    const outputFileStream = new FileWriter('./output.wav', {
      sampleRate: 44100,
      channels: 1
    });
    stream.pipe(outputFileStream);
    // console.log(data);
    // stream.push(data);
  })
})
```

**Client.js**
```javascript
const getUserMedia = require('get-user-media-promise');
var MicrophoneStream = require('microphone-stream');

const socket = new eio.Socket('ws://localhost:4000');

socket.on('open', () => {
  console.log('Sup from client');
})

function init() {  
  const startCasting = document.getElementById('start-casting');
  const stopCasting = document.getElementById('stop-casting');
  const playStream = document.getElementById('play-stream');

  // socket.send('Hello From Client')

  socket.on('open', () => {
    playStream.onclick = () => {
      // socket.send('Play Stream');
    }
  })

  

  startCasting.onclick = () => {
    // Disable the button
    startCasting.setAttribute('disabled', 'disabled');
    stopCasting.removeAttribute('disabled');
    const micStream = new MicrophoneStream();
    // socket.send('Start Caasting');

    getUserMedia({ video: false, audio: true })
      .then(function(stream) {
        console.log('Got Stream');
        micStream.setStream(stream);
      }).catch(function(error) {
        console.log(error);
      });
    
    micStream.on('data', (chunk) => {
      console.log('Got data from mic');
      socket.send(chunk);
    });

    micStream.on('format', (format) => {
      console.log(format);
    });

    stopCasting.onclick = () => {
      // 'Stop'
      micStream.stop();
      startCasting.removeAttribute('disabled');
      stopCasting.setAttribute('disabled', 'disabled');
    };
  }
  
}

init();
```

**Comment by nfriedly** [comment]
Hi @mshaaban0 

This approach sounds feasible, but you might also have good results by using the [WebRTC API](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API)

One thing to note for your approach is that the WebAudio API uses a less common audio format consisting of 32-bit floating point numbers for each sample. Most .wav files instead use 16-bit Integers. The Watson Speech JS SDK has an (open source) [method](https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/speech-to-text/webaudio-l16-stream.js#L152) to convert web audio to "raw wav" format ("raw" because it's missing the .wav header. However, [node-wav](https://www.npmjs.com/package/wav) can add that.)

**Comment by mshaaban0** [comment]
@nfriedly Thanks for the help. I also considered WebRTC for this, but haven't give it a try, yet!
I guess I'll now and run some benchmarks to see which performs better. I'll update this issue for the good of all once I've more details. Thanks again.

**Comment by jamauro** [comment]
@mshaaban0 curious, what did you end up doing? I’m looking at doing something similar to what you posted above but wondering if you ran into any roadblocks or ended up deciding WebRTC was better.

**Comment by mshaaban0** [comment]
@jamauro WebRTC is not meant to handle high traffic, as it relies heavily on the broadcaster machine [check here](https://stackoverflow.com/questions/28590423/webrtc-cpu-reduction-settings-to-tweak). I didn't get enough time to work on the project, but anyway I recommend to consider streaming with tcp protocol, try out the `net` [module](https://nodejs.org/api/net.html#net_net) from node.
