### ISSUE TITLE
What is licence of the project?

### ISSUE THREAD

**Issue by farooqkz** [saebekassebil/microphone-stream#26]
Hello. You haven't specified a licence so according to Berne convention it's "All rights reserved" so no one can use it or anything else.

**Comment by nfriedly** [comment]
It's MIT licensed, as declared in the package.json (which is the standard place to declare the license of a node.js project): https://github.com/saebekassebil/microphone-stream/blob/699aa9ddb241192ff97fafe495558d64a49035c1/package.json#L33
