### ISSUE TITLE
Consider transfering saebekassebil/microphone-stream to nfriedly/microphone-stream 

### ISSUE THREAD

**Issue by nfriedly** [saebekassebil/microphone-stream#35]
Hey @saebekassebil, would you be willing to transfer this repo to me?

I just realized that github doesn't notify me of security vulns for this repo, so when I happened to test it locally there were quite a few (mostly in dev dependencies). They're all fixed now, but if we transferred it over to my account, I'd be able to stay on top of it a little better. 

Also, there were some old issues that fell through the cracks, because I tend to just filter to repos I own in order to cut out the noise from my work, but that then omits this one too.

**Comment by trivikr** [comment]
As a new consumer of microphone-stream package, I looked at the contributor graph and recent commits. @nfriedly clearly shows ownership of this package.

Contributor graph: https://github.com/saebekassebil/microphone-stream/graphs/contributors

<details>
<summary>Contributor graph screenshot</summary>

![Screen Shot 2021-02-03 at 8 18 30 AM](https://user-images.githubusercontent.com/16024985/106776786-3c6d7300-65f9-11eb-8da0-2fdbb521978f.png)

</details>

Other option is to [create a new organization](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-new-organization-from-scratch) (say `microphone-stream`), and [transferring this repository](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository) to that organization.

**Comment by saebekassebil** [comment]
Hey @nfriedly! Thank you for taking over this package and making it useful :) I'll transfer the repo to you, since you're basically now the main author of the repo and I'm sadly not active in the open source community right now. Best of luck :)

**Comment by saebekassebil** [comment]
Woops. Okay just tried, but since you have a similar-named repo (microphone-stream) I can't transfer it to you. You'd probably need to rename/remove it before. Let me know if you're still interested.

**Comment by nfriedly** [comment]
Oh, hah, that was my fork of this repo. I deleted it now. Want to try again?

**Comment by nfriedly** [comment]
Actually, I'm starting to wonder if we should transfer this to @trivikr - I'm not longer actively using it and they obviously are, so they might be a better steward. What do you guys think?

**Comment by nfriedly** [comment]
(Or I suppose we could stick it in an org and grant access to all three of us)

**Comment by trivikr** [comment]
> I suppose we could stick it in an org and grant access to all three of us.

Yup, I too think we should create an org (say [`microphone-stream`](https://github.com/microphone-stream)) so that ownership can be shared based on who is using the project.

I'm currently using it in a demo app [aws-sdk-js-notes-app](https://github.com/aws-samples/aws-sdk-js-notes-app), and would be interested in improving Developer Experience. I don't mind being a collaborator.

**Comment by nfriedly** [comment]
Alright, I set up https://github.com/microphone-stream and invited both of you. @saebekassebil, if you please, transfer the repo there.

**Comment by saebekassebil** [comment]
Done
