### ISSUE TITLE
Expose internal nodes for more connections

### ISSUE THREAD

**Issue by yomed** [saebekassebil/microphone-stream#36]
Hi, I am looking into connecting an `analyser` to the input node created through `new MicrophoneStream()` for a visualization. So something like this:
```js
const micStream = new MicrophoneStream({ context: audioContext });
const analyser = audioContext.createAnalyser();
micStream.audioInput.connect(analyser); // NOTE: can't do this yet
```

In this case I was looking at adding the `analyser` to get access to its methods like:
```js
analyser.getByteTimeDomainData(data);
```

Does it make sense to expose `micStream.audioInput` for this purpose?
I'm not sure if I'm misunderstanding -- is the `analyser` unnecessary since the raw data is already accessible?

**Comment by nfriedly** [comment]
Honestly, I'm not sure. You can probably get what you need from the output of this library, but it might be better formatted or more efficient to get it out of an AnalyserNode. I don't know much about those.

Do you need the audio data for anything else? If not, you might be able to just skip it.

If you do need the audio to go to someplace besides your visualization, you can definitely `pipe()` this library's output to two places.

But, if you want to try out the AnalyserNode, I might recommend first trying to create two audioInputs, something like this  - although I'm not sure if that will work in any/all browsers:

```js
  const AudioContext = window.AudioContext || window.webkitAudioContext;
  const audioContext = new AudioContext();
  const analyser = audioContext.createAnalyser();
  const micStream = new MicrophoneStream({ context: audioContext });

 getUserMedia({ video: false, audio: true })
    .then(function(stream) {
      micStream.setStream(stream); // creates first MediaStreamSource
      const audioInput2 = context.createMediaStreamSource(stream); // creates second MediaStreamSource (?)
      audioInput2.connect(analyser);
    }).catch(function(error) {
      console.log(error);
    });
```

If that fails, then yea, exposing the audioInput from this library should work. Just send us a PR for it.  

One thing I'll mention is that in your example code, you didn't provide the stream, and the `audioInput` doesn't get created unless a stream is passed into the constructor or `setStream()` is called, so `audioInput` would be `undefined` until then.

**Comment by yomed** [comment]
Thanks for those details. Yes, in this case I need the `analyser` for the easy access to visualization methods, and also I need the original raw data for my own processing. I gave your sample a try, and it seems to work in Chrome, but has issues in Safari (the `analyser` works fine, but the original `micStream.on('data')` stops firing).

From testing locally, it does seem like exposing the original `audioInput` solves this issue. I'll send a PR, thanks!
