### ISSUE TITLE
Built-in TypeScript types for microphone-stream

### ISSUE THREAD

**Issue by trivikr** [saebekassebil/microphone-stream#39]
### Is your feature request related to a problem? Please describe.
The package [microphone-stream](https://www.npmjs.com/package/microphone-stream) neither provides built-in types nor it's type definitions are available in DefinitelyTyped.
* The types field is not present in [package.json](https://github.com/saebekassebil/microphone-stream/blob/4af20529a204a97673a8968982eed17275ea7811/package.json).
* The npm package [@types/microphone-stream](https://www.npmjs.com/package/@types/microphone-stream) is not present.

Because of the missing TypeScript types, if microphone-stream is consumed in a TypeScript project the following error is shown:

TypeScript code:
```ts
import * as MicrophoneStream from "microphone-stream";
```

Error:
```console
Could not find a declaration file for module 'microphone-stream'. '/Users/trivikr/workspace/aws-sdk-js-notes-app/node_modules/microphone-stream/microphone-stream.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/microphone-stream` if it exists or add a new declaration (.d.ts) file containing `declare module 'microphone-stream';`ts(7016)
```

<details>
<summary>Screenshot</summary>

![Screen Shot 2021-02-03 at 8 01 01 AM](https://user-images.githubusercontent.com/16024985/106773590-15617200-65f6-11eb-8f69-c28b2094412e.png)

</details>

### Describe the solution you'd like
Add built-in TypeScript types for microphone-stream.
* With TypeScript 3.7, TypeScript added support for [generating .d.ts files from JavaScript using JSDoc syntax](https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html).
* [dts-gen](https://github.com/microsoft/dts-gen) creates starter TypeScript definition files for any module or library.

### Describe alternatives you've considered
To resolve this error, the TypeScript project consuming the package either have to:
* add `@ts-ignore` to ignore the missing types.
* add `@types/microphone-stream/index.d.ts` in the root of the project.

### Additional context
Refs: https://github.com/aws-samples/aws-sdk-js-notes-app/pull/7

**Comment by nfriedly** [comment]
I don't have a ton of experience with TypeScript, but this seems like a good idea.  Do you think you can do the legwork here to make it generate types automatically, maybe as a `preversion` or `version` npm run script? (https://docs.npmjs.com/cli/v6/commands/npm-version)

**Comment by trivikr** [comment]
Experimental commits to add TypeScript types can be viewed in https://github.com/trivikr/microphone-stream/commits/add-types

It's currently blocked at the following error if anyone wants to pick up:
```console
src/microphone-stream.js:1:1 - error TS9005: Declaration emit for this file requires using private name 'setStream'. An explicit type annotation may unblock declaration emit.

1 'use strict';
  ~~~~~~~~~~~~


Found 1 error.
```

Commit which added `setStream` for reference: https://github.com/saebekassebil/microphone-stream/commit/ef410f90933b58de0c50a57fa7672099cc7769ae

**Comment by trivikr** [comment]
Whoever picks this up in future, the most helpful discussion for TS9005 error I could find online is at https://stackoverflow.com/questions/63653098

**Comment by trivikr** [comment]
Type definitions were added in https://github.com/saebekassebil/microphone-stream/pull/40
