### ISSUE TITLE
Enable Travis-CI

### ISSUE THREAD

**Issue by nfriedly** [saebekassebil/microphone-stream#4]
Hi, If you haven't heard of it, Travis-CI is a handy service that can automatically run your tests after every code push, and it integrates nicely with github for pull requests and such.

I set up the tests and verified that things are working with my fork but I can't enable it for your repo (even with push access).

I think you can just go to https://travis-ci.org/profile/saebekassebil, login with your github account (oauth), and flip the switch. It should be fairly straightforward even if that's not exactly right.

**Comment by saebekassebil** [comment]
I know travis but with no test it didn't make a lot of sense to include. Thanks for writing those test - I've added Travis build info from 3794d278fabb661d4756ac1c3ad60ebbfd768a69

Cheers Nathan!

**Comment by nfriedly** [comment]
:+1:
