### ISSUE TITLE
Rename the default branch from master to main?

### ISSUE THREAD

**Issue by trivikr** [saebekassebil/microphone-stream#42]
### Is your feature request related to a problem? Please describe.
Many communities, both on GitHub and in the wider Git community, are renaming the default branch name of their repositories from `master` to be inclusive.

### Describe the solution you'd like
Rename the default branch to `main` for microphone-stream, and delete `master` branch.
GitHub has made it very easy to rename default branches https://github.com/github/renaming#renaming-existing-branches

### Describe alternatives you've considered
Stick with `master` as default branch

**Comment by trivikr** [comment]
@microphone-stream/core I plan to make this change in couple of days if you don't have any objection.

**Comment by nfriedly** [comment]
Sounds good to me.

**Comment by trivikr** [comment]
The default branch is now https://github.com/microphone-stream/microphone-stream/tree/main  🎉
