### ISSUE TITLE
Use Github Actions to run CI and publish

### ISSUE THREAD

**Issue by trivikr** [saebekassebil/microphone-stream#43]
### Is your feature request related to a problem? Please describe.
Not an issue right now, but Travis CI added [new pricing in Nov 2020](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing#what-do-the-pricing-changes-mean), with only 1000 minutes available for public repositories.
Many [OSS developers](https://twitter.com/search?q=travis%20ci%20oss%20until%3A2020-12-01%20since%3A2020-11-01&src=typed_query) moved away from Travis in a hurry as a result.

### Describe the solution you'd like
Use GitHub Actions to run CI and publish.

### Describe alternatives you've considered
Stick to Travis CI, as microphone-stream is not actively worked on.

### Additional context
Babel uses GitHub Actions for publishing https://twitter.com/NicoloRibaudo/status/1357449597375897601

**Comment by nfriedly** [comment]
Yea, I've been slowly moving things off of Travis, but this hasn't been a high priority. microphone-stream needs a working browser to run the tests in, and I didn't feel like figuring that out again. But, if you want to give it a shot, feel free.
