### ISSUE TITLE
Use ES6 class and extends keywords instead of util.inherits

### ISSUE THREAD

**Issue by trivikr** [saebekassebil/microphone-stream#46]
### Is your feature request related to a problem? Please describe.
Usage of util.inherits is discouraged in Node.js docs https://nodejs.org/api/util.html#util_util_inherits_constructor_superconstructor

### Describe the solution you'd like
Use ES6 class and extends keywords to get language level inheritance support. If we still plan to support ES5 browsers, this can be combined with moving to TypeScript in https://github.com/microphone-stream/microphone-stream/issues/41

**Comment by nfriedly** [comment]
Yea, this makes sense if we switch it to typescript.
