### ISSUE TITLE
playback of recorded PCM data speeds up.

### ISSUE THREAD

**Issue by jackiosport** [saebekassebil/microphone-stream#51]
## Describe the bug
creating an [audiobuffer](https://developer.mozilla.org/en-US/docs/Web/API/AudioBuffer/AudioBuffer) from the raw PCM data from microphone-stream does not playback correctly when it is used as the buffer to an [audioBufferSourceNode](https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode)

## Steps to reproduce
I record the raw data from the microphone using MicrophoneStream
```
const chunks = [];
const micStream = new MicrophoneStream();
micStream.on('data', (chunk)=> {
            const raw = MicrophoneStream.toRaw(chunk);
            chunks.push(raw);
})
```

I flatten all the float32s with with this function:

```
const float32Flatten = (chunks) => {
    const nFrames = chunks.reduce((acc, elem) => acc + elem.length, 0)
    const result = new Float32Array(nFrames);
    let currentFrame =0
    chunks.forEach((chunk)=> {
        result.set(chunk, currentFrame)
        currentFrame += chunk.length;
    });
    return result;
 }

``` 
so now we can use the above functin to create one big float32array which we put into an audiobuffer.

```
const rawData = float32Flatten(chunks);
const audioBuffer = ctx.createBuffer(0, rawData.length, 48000);
audioBuffer.copyToChannel(rawData, 0, 0);
```

we now make an audio source node and play back!

```
const sourceNode = ctx.createBufferSource();
sourceNode.buffer= audioBuffer;
sourceNode.connect(ctx.destination);
sourceNode.start()
```

#### Observed behavior
The playback audio speeds up as in plays back.

**Comment by jackiosport** [comment]
I have been thinking about, does each chunk handled in the MicrophoneStream `on('data')...` have the same samplerate? Or can it vary? 

If it varys this would change the playback rate.

**Comment by jackiosport** [comment]
> I have been thinking about, does each chunk handled in the MicrophoneStream `on('data')...` have the same samplerate? Or can it vary?
> 
> If it varys this would change the playback rate.

This line of reasoning is wrong.. Printed out the samplerate throughout the recording using `on('format')`and it was only ever:
```
sampleRate: 48000
```

**Comment by nfriedly** [comment]
I'm not sure... does it work properly if you bypass MicrophoneStream and grab the data yourself?

**Comment by jackiosport** [comment]
> I'm not sure... does it work properly if you bypass MicrophoneStream and grab the data yourself?

@nfriedly Do you mean by using a [scriptprocessornode](https://developer.mozilla.org/en-US/docs/Web/API/ScriptProcessorNode)?

**Comment by nfriedly** [comment]
Yes

**Comment by jackiosport** [comment]
I found the issue. Is to do with with following: https://bugs.chromium.org/p/chromium/issues/detail?id=650425.
that is the scriptporcessor used by microphone-stream gets blocked by other processes and it doesnt get to process the raw data.

I could stop this bug by increasing the buffer size in the opts to microphone stream like this.
```const micStream = new MicrophoneStream({bufferSize:16384})```

Perhaps it may be worth considering writing microphone-stream with an audioworklet see:

 https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Using_AudioWorklet

Closing the issue for now. Thanks for your help @nfriedly !

**Comment by nfriedly** [comment]
Aah, I see. @trivikr was just talking about switching to AudioWorklet in #47

**Comment by trivikr** [comment]
I'll evaluate switching to Audio Workers after we move to TypeScript in https://github.com/microphone-stream/microphone-stream/pull/48

**Comment by jackiosport** [comment]
Let me know if you want some help! I have been experimenting with AudioWorkelts.

**Comment by trivikr** [comment]
> Let me know if you want some help! I have been experimenting with AudioWorkelts.

Thank you @jackiosport 
Can I assign issue https://github.com/microphone-stream/microphone-stream/issues/47 to you? I'll comment on it once migration to TypeScript is complete.

The TypeScript PR is ready at https://github.com/microphone-stream/microphone-stream/pull/48.
I expect review and merge to take around two weeks since it would be a major version bump. You're welcome to review it if you're interested in TypeScript :+1:

**Comment by jackiosport** [comment]
Hello yes I am currently re-rearching worklets! I will think about how they can be used in this libary so that #47 can be workd on.
