### ISSUE TITLE
Need to use require().default in v6

### ISSUE THREAD

**Issue by yomed** [saebekassebil/microphone-stream#55]
## Describe the bug
In my application, I use `require` importing instead of `import`.
In v5, I used `const MicrophoneStream = require('microphone-stream')`
In v6, it appears this must be changed to `const MicrophoneStream = require('microphone-stream').default`

If this change is desired, I can help with documentation for differences in using this with `import` and `require`.

#### Version number
`microphone-stream@6.0.0`

**Comment by nfriedly** [comment]
Yea, I think that was probably an oversight. If you want to send a PR to update the readme with correct examples for `import` and `require`, that would be appreciated.
