### ISSUE TITLE
The spec of data?

### ISSUE THREAD

**Issue by darkyen** [saebekassebil/microphone-stream#6]
I would like to use the output of the stream here to be fed to a lame / ffmpeg encoder on the server side, the data is streamed to server using websockets. I wonder can I treat the 8bitBuffer returned by this module as bitDepth 8 samples?

**Comment by darkyen** [comment]
My bad :-| should just use the format event!

**Comment by nfriedly** [comment]
:)

Yea, the 8-bit stuff is just to play nice with the Node.is Streams API, its actually a Float32Array.

Take a look at https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/speech-to-text/webaudio-l16-stream.js if you'd like to see an example of down sampling and converting to 16-bit little edian (raw WAV format)

**Comment by darkyen** [comment]
Ha, I re-implemented what you linked me after spending some time reading
about audio compression, it also plays nice with node-style streams.
Although they must be float32 so far. (so like yours)
​
