### ISSUE TITLE
Help, sending raw stream to a server end point

### ISSUE THREAD

**Issue by cubecleveland** [saebekassebil/microphone-stream#62]
Hi, stumble upon this great wrapper.

We are trying to send raw packets received from mic to a server endpoint live.
So as data is recieved it is transfered in a keep alive connection to a server endpoint.
CAn u send some instruction on how that can be achived...

P.S

I am pretty sure we can use Fetch stream to deliver to the endpoint without and proxy servers...

Any help will be gratlly appreciated.

**Comment by nfriedly** [comment]
I've never used Fetch for streaming before, I've used WebSockets. The watson-speech SDK uses this approach (with this library) and has lots of examples:

https://github.com/watson-developer-cloud/speech-javascript-sdk
https://speech-to-text-demo.ng.bluemix.net

If you need more help, I can probably free up a few hours for consulting. Send me an email and we can discuss that if you'd like.

**Comment by cubecleveland** [comment]
How can we get in touch ?


CUBE Workspace
Corporate: 6240 Som Center Rd #130
Solon, OH 44139
T: 216.245.9629

**Comment by nfriedly** [comment]
nathan@incline.digital
