### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by ashwinkumar6** [saebekassebil/microphone-stream#82]
## Describe the bug
Creating a microphoneStream using the code below throws the following error.
Attached screenshots for the same at the end

```js
import {default as MicrophoneStream} from "microphone-stream";

document.getElementById("startRecordButton").onclick = function startRecord () {
  try {
    const micStream = new MicrophoneStream();

    window.navigator.mediaDevices.getUserMedia({ video: false, audio: true })
      .then(function (stream) {
        micStream.setStream(stream);

        micStream.on('data', function (chunk) {
          const raw = MicrophoneStream.toRaw(chunk)
          console.log("raw", raw);
        });

        micStream.on('format', function (format) {
          console.log("format", format);
        });

      }).catch(function (error) {
        console.log("unable to create mic stream", error);
      });

  } catch (err) {
    console.log("Error. ", err);
  }
};
```
**Error**
``` 
Uncaught ReferenceError: process is not defined
    at maybeReadMore (_stream_readable.js:561:1)
    at addChunk (_stream_readable.js:306:1)
    at readableAddChunk (_stream_readable.js:280:1)
    at Readable.push (_stream_readable.js:241:1)
    at ScriptProcessorNode.recorderProcess (microphone-stream.js:108:1)
```

## Additional context

The error seems to be coming from the `readable-stream` package in _stream_readable.js file line561
`process.nextTick(maybeReadMore_, stream, state);`
I believe process.nextTick is a NodeJS specific API and isn't available on the browser. setTimeout should be used instead

## Screenshots
![Screen Shot 2022-07-19 at 2 31 21 PM](https://user-images.githubusercontent.com/22762119/179852108-87e1aee9-1da3-4363-9ffb-98d3aa07fff0.png)
![Screen Shot 2022-07-19 at 2 31 35 PM](https://user-images.githubusercontent.com/22762119/179852122-76daca06-f043-4e13-90ed-56e7521c5534.png)

## Your environment
OS: macOS Monterey (12.3.1)
Node: 16.15.1

#### Version number
`microphone-stream@6.0.1`

#### Is the issue in the browser/Node.js?
Browser

#### Details of the browser/Node.js version
Chrome: 103.0.5060.134

**Comment by ashwinkumar6** [comment]
Created an [issue](https://github.com/nodejs/readable-stream/issues/480) for this on [readable-stream](https://github.com/nodejs/readable-stream) as well

Is there any workaround for this at the moment ?

**Comment by nfriedly** [comment]
This sounds similar to #75 - are you using webpack 5?

**Comment by ashwinkumar6** [comment]
ah yes, it's the webpack 5 issue. Webpack 5 doesn't Polyfill which causes this issue.
Didn't notice another open issue for this.
