### ISSUE TITLE
Question: How to do this same thing for an audio file loaded with createObjectURL and a stream from captureStream?

### ISSUE THREAD

**Issue by rmtuckerphx** [saebekassebil/microphone-stream#89]
I want the user to be able to use the microphone OR load an audio file on the web page and then stream the audio.

Here is the code I'm starting with, but not sure how to process the stream.

		fileURL = URL.createObjectURL(files[0]);
		audioSource = new Audio(fileURL);
		stream = audioSource.captureStream();

**Comment by nfriedly** [comment]
Take a look at the Watson speech library, it can handle audio from a local file, a microphone, or a URL: https://github.com/watson-developer-cloud/speech-javascript-sdk
